version: '3.8'

services:
  # Spring Boot Application
  app:
    build: .
    container_name: huynhgia-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://root:RPUDoNabMnAdUFEacCRNVYxfsqJMkFeI@crossover.proxy.rlwy.net:31040/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: RPUDoNabMnAdUFEacCRNVYxfsqJMkFeI
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_PROFILES_ACTIVE: docker

networks:
  default:
    driver: bridge

 